import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";

import { AutonomousEntity, AutonomousEntities } from "../data";
import { AE } from "../components/AE";
import { AnimatePresence } from "framer-motion";

const Home: NextPage = () => {
  const [AERouter, setAERouter] = useState<AutonomousEntity[]>([]);

  useEffect(() => {
    const firstAE = AutonomousEntities.get("1");

    if (firstAE) setAERouter([firstAE]);
  }, []);

  const handleOnGoToAE = (index: string) => {
    const AEData = AutonomousEntities.get(index);

    if (!AEData) return;

    setAERouter((state) => [...state, AEData]);
  };

  return (
    <div className="w-screen h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-medium mt-8 text-center">Chartreuse</h1>
      <main className="w-full h-full grid content-center">
        <div className="mx-auto relative md:max-w-[680px]">
          <AnimatePresence>
            {AERouter.map((data, i) => (
              <AE
                {...data}
                key={i}
                onGoToAE={handleOnGoToAE}
                level={i}
                currentStackLength={AERouter.length}
              />
            ))}
          </AnimatePresence>
        </div>
      </main>
    </div>
  );
};

export default Home;
