import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";

import { AutonomousEntity, AutonomousEntities } from "../data";
import { AE } from "../components/AE";

const Home: NextPage = () => {
  const [AERouter, setAERouter] = useState<AutonomousEntity[]>([]);

  useEffect(() => {
    const firstAE = AutonomousEntities.get("1");

    if (firstAE) setAERouter([firstAE]);
  }, []);

  const handleOnGoToAE = (index: string) => {
    const AEData = AutonomousEntities.get(index);

    if (!AEData) return;

    setAERouter((state) => [...state, AEData]);
  };

  return (
    <div className="w-screen h-screen grid ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto container">
        <h1 className="text-2xl font-medium mt-8">Chartreuse</h1>

        <div className="relative max-w-[400px] mt-8">
          {AERouter.map((data, i) => (
            <AE
              {...data}
              key={i}
              onGoToAE={handleOnGoToAE}
              level={i}
              currentStackLength={AERouter.length}
            />
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;
